local statusEntries = {
  "Playing jr!help",
  "Watching for rule breakers",
  "Competing in Obby Creator Build Battles",
  "Watching Blue say wt",
  "Playing some grand piano",
  "Playing in Jr's website",
  "Watching the JDC4 trailers",
  "Watching Jr go brrrrrrrrrr",
  "Watching people DM staff members",
  "Listening to #fact-of-the-day",
  "Playing no",
  "Competing in the Tokyo 2020 olympics",
  "Playing JDC4",
  "Playing JDC6",
  "Playing Blackout V1: 6273091854",
  "Watching Jr's YouTube channel",
  "Listening to Jryptix's soundtracks",
  "Playing Jr's roblox games",
  "Playing with Jr",
  "Listening to Jr's Flood Escape OST",
  "Watching people beat FE2 highlights",
  "Watching Blue say me when",
  "Watching Jr scripting",
  "Watching #one-word-story",
  "Watching Atlantis go brrrrrrrr",
  "Listening to silence",
  "Listening to FE2CM OSTs",
  "Watching Jr make OSTs",
  "Playing Sublevel 469",
  "Playing Sublevel 696",
  "Playing Sol's (gambling) RNG",
  "Watching Jr go offline",
  "Watching Blue go offline",
  "Listening to e",
  "Playing difficulty chart obbies",
  "Playing PaRYM maps",
  "Watching FOTD posters",
  "Listening to you",
  "Listening to FE2 drama",
  "Listening to ROBLOX Drama",
  "Listening to haters from TRIA",
}

print(#statusEntries)
